export const ROOM_TESTER_LEVELS = [
  {
    kind: "assembled",
    tileSetId: "scenarioDefault",
    name: "Room Tester: enter + treasure_03 + treasure_04 + exit",
    connectorStyleId: "openCorridor",
    enemyDifficulty: "easy",
    decorationFill: {
      seed: "random",
      modules: [
        {
          moduleId: "floorDetail",
          density: 0.3,
        },
        {
          moduleId: "barrel",
          density: 1,
          roomTypes: ["combat", "treasure"],
          spotStrategy: "semantic",
          spotTypes: ["corner", "door", "chest"],
          spotMinDistance: 5,
          spotInset: 1.4,
          doorSpotDepth: 2.2,
          doorSpotSideOffset: 2,
          chestSpotOffset: 1.8,
          clustersPerRoom: { min: 3, max: 5 },
          clusterSize: { min: 2, max: 5 },
          clusterRadius: 1,
          clusterScatterRadius: 0.4,
          placementFootprint: { w: 0.6, d: 0.6 },
          collisionFootprint: { w: 0.1, d: 0.1 },
          positionJitter: 1,
          scaleVariation: { min: 0.8, max: 1.6 },
        },
        {
          moduleId: "stones",
          density: 0.05,
          zoneTypes: null,
          allowUnzoned: true,
          placementFootprint: { w: 0.35, d: 0.35 },
          positionJitter: 0.35,
          scaleVariation: { min: 0.5, max: 1.2 },
        },
      ],
    },
    playerStart: { x: -21, z: 0 },
    floorSize: 70,
    floorCenter: { x: -5.5, z: 0 },
    rooms: [
      {
        id: "TesterEnter",
        templateId: "enter_room_east_west_01",
        position: { x: -20, z: 0 },
        rotationY: 0,
      },
      {
        id: "TesterTreasure03",
        templateId: "treasure_03",
        position: { x: -13, z: 0 },
        rotationY: 0,
      },
      {
        id: "TesterTreasure04",
        templateId: "treasure_04",
        position: { x: -2, z: 0 },
        rotationY: 0,
      },
      {
        id: "TesterExit",
        templateId: "exit_room_east_west_01",
        position: { x: 9, z: 0 },
        rotationY: 0,
      },
    ],
  },
];
