export const EXIT_ROOM_TEMPLATES = [
  {
    id: "exit_room_north_south_01",
    type: "exit",
    name: "North/South Exit 01",
    dimensions: { w: 9, d: 9 },
    floorModules: [
      {
        x: 0,
        z: 0,
        w: 9,
        d: 9,
        moduleId: "floor",
      },
    ],
    walkableAreas: [
      {
        x: 0,
        z: 0,
        w: 9,
        d: 9,
      },
    ],
    wallModules: [
      {
        x: -4,
        z: -4,
        w: 1,
        d: 1,
        corner: "northWest",
        rotationY: 0,
        moduleId: "wallCorner",
      },
      {
        x: 4,
        z: -4,
        w: 1,
        d: 1,
        corner: "northEast",
        rotationY: Math.PI / 2,
        moduleId: "wallCorner",
      },
      {
        x: 4,
        z: 4,
        w: 1,
        d: 1,
        corner: "southEast",
        rotationY: Math.PI,
        moduleId: "wallCorner",
      },
      {
        x: -4,
        z: 4,
        w: 1,
        d: 1,
        corner: "southWest",
        rotationY: -Math.PI / 2,
        moduleId: "wallCorner",
      },
      {
        x: -2.5,
        z: -4,
        w: 2,
        d: 1,
        side: "north",
        rotationY: 0,
        moduleId: "wallHalf",
      },
      {
        x: 2.5,
        z: -4,
        w: 2,
        d: 1,
        side: "north",
        rotationY: 0,
        moduleId: "wallHalf",
      },
      {
        x: -2.5,
        z: 4,
        w: 2,
        d: 1,
        side: "south",
        rotationY: Math.PI,
        moduleId: "wallHalf",
      },
      {
        x: 2.5,
        z: 4,
        w: 2,
        d: 1,
        side: "south",
        rotationY: Math.PI,
        moduleId: "wallHalf",
      },
      {
        x: -4,
        z: 0,
        w: 1,
        d: 7,
        side: "west",
        rotationY: Math.PI / 2,
        moduleId: "wallHalf",
      },
      {
        x: 4,
        z: 0,
        w: 1,
        d: 7,
        side: "east",
        rotationY: -Math.PI / 2,
        moduleId: "wallHalf",
      },
    ],
    doorwayModules: [
      {
        x: 0,
        z: -4,
        w: 5,
        d: 1,
        side: "north",
        rotationY: 0,
        moduleId: "wallHalf",
      },
      {
        x: 0,
        z: 4,
        w: 5,
        d: 1,
        side: "south",
        rotationY: Math.PI,
        moduleId: "wallHalf",
      },
    ],
    doorOpenings: [
      { side: "north", offset: 0, width: 1, exitStairsRotationY: Math.PI },
      { side: "south", offset: 0, width: 1, exitStairsRotationY: 0 },
    ],
    enemySpawns: [],
    chestSpawns: [
      {
        x: -2.8,
        z: -3,
        rotationY: 0,
        modelId: "chest_01",
      },
    ],
    exitMarker: null,
    setDressingModules: [
      {
        x: -3.45,
        z: 0,
        w: 1,
        d: 1,
        side: "west",
        rotationY: Math.PI / 2,
        moduleId: "banner",
      },
      {
        x: 3.45,
        z: 0,
        w: 1,
        d: 1,
        side: "east",
        rotationY: -Math.PI / 2,
        moduleId: "banner",
      },
    ],
    obstacleModules: [],
  },
  {
    id: "exit_room_east_west_01",
    type: "exit",
    name: "East/West Exit 01",
    dimensions: { w: 7, d: 7 },
    floorModules: [
      {
        x: 0,
        z: 0,
        w: 7,
        d: 7,
        moduleId: "floor",
      },
    ],
    walkableAreas: [
      {
        x: 0,
        z: 0,
        w: 7,
        d: 7,
      },
    ],
    wallModules: [
      {
        x: -3,
        z: -3,
        w: 1,
        d: 1,
        corner: "northWest",
        rotationY: 0,
        moduleId: "wallCorner",
      },
      {
        x: 3,
        z: -3,
        w: 1,
        d: 1,
        corner: "northEast",
        rotationY: Math.PI / 2,
        moduleId: "wallCorner",
      },
      {
        x: 3,
        z: 3,
        w: 1,
        d: 1,
        corner: "southEast",
        rotationY: Math.PI,
        moduleId: "wallCorner",
      },
      {
        x: -3,
        z: 3,
        w: 1,
        d: 1,
        corner: "southWest",
        rotationY: -Math.PI / 2,
        moduleId: "wallCorner",
      },
      {
        x: 0,
        z: -3,
        w: 5,
        d: 1,
        side: "north",
        rotationY: 0,
        moduleId: "wallHalf",
      },
      {
        x: 0,
        z: 3,
        w: 5,
        d: 1,
        side: "south",
        rotationY: Math.PI,
        moduleId: "wallHalf",
      },
      {
        x: -3,
        z: -2,
        w: 1,
        d: 1,
        side: "west",
        rotationY: Math.PI / 2,
        moduleId: "wallHalf",
      },
      {
        x: -3,
        z: 2,
        w: 1,
        d: 1,
        side: "west",
        rotationY: Math.PI / 2,
        moduleId: "wallHalf",
      },
      {
        x: 3,
        z: -2,
        w: 1,
        d: 1,
        side: "east",
        rotationY: -Math.PI / 2,
        moduleId: "wallHalf",
      },
      {
        x: 3,
        z: 2,
        w: 1,
        d: 1,
        side: "east",
        rotationY: -Math.PI / 2,
        moduleId: "wallHalf",
      },
    ],
    doorwayModules: [
      {
        x: -3,
        z: 0,
        w: 1,
        d: 3,
        side: "west",
        rotationY: Math.PI / 2,
        moduleId: "wallHalf",
      },
      {
        x: 3,
        z: 0,
        w: 1,
        d: 3,
        side: "east",
        rotationY: -Math.PI / 2,
        moduleId: "wallHalf",
      },
    ],
    doorOpenings: [
      { side: "west", offset: 0, width: 1, exitStairsRotationY: -Math.PI / 2 },
      { side: "east", offset: 0, width: 1, exitStairsRotationY: Math.PI / 2 },
    ],
    enemySpawns: [],
    chestSpawns: [
      {
        x: 1.9,
        z: -2.1,
        rotationY: -Math.PI / 2,
        modelId: "chest_01",
      },
    ],
    exitMarker: null,
    setDressingModules: [
      {
        x: 0,
        z: -2.45,
        w: 1,
        d: 1,
        side: "north",
        rotationY: Math.PI,
        moduleId: "banner",
      },
      {
        x: 0,
        z: 2.45,
        w: 1,
        d: 1,
        side: "south",
        rotationY: 0,
        moduleId: "banner",
      },
    ],
    obstacleModules: [],
  },
  {
    id: "exit_room_north_south_02",
    type: "exit",
    name: "North/South Exit 02",
    dimensions: { w: 5, d: 11 },
    floorModules: [
      {
        x: 0,
        z: 0,
        w: 5,
        d: 11,
        moduleId: "floor",
      },
    ],
    walkableAreas: [
      {
        x: 0,
        z: 0,
        w: 5,
        d: 11,
      },
    ],
    wallModules: [
      {
        x: -2,
        z: -5,
        w: 1,
        d: 1,
        corner: "northWest",
        rotationY: 0,
        moduleId: "wallCorner",
      },
      {
        x: 2,
        z: -5,
        w: 1,
        d: 1,
        corner: "northEast",
        rotationY: Math.PI / 2,
        moduleId: "wallCorner",
      },
      {
        x: 2,
        z: 5,
        w: 1,
        d: 1,
        corner: "southEast",
        rotationY: Math.PI,
        moduleId: "wallCorner",
      },
      {
        x: -2,
        z: 5,
        w: 1,
        d: 1,
        corner: "southWest",
        rotationY: -Math.PI / 2,
        moduleId: "wallCorner",
      },
      {
        x: -2,
        z: 0,
        w: 1,
        d: 9,
        side: "west",
        rotationY: Math.PI / 2,
        moduleId: "wallHalf",
      },
      {
        x: 2,
        z: 0,
        w: 1,
        d: 9,
        side: "east",
        rotationY: -Math.PI / 2,
        moduleId: "wallHalf",
      },
    ],
    doorwayModules: [
      {
        x: 0,
        z: -5,
        w: 3,
        d: 1,
        side: "north",
        rotationY: 0,
        moduleId: "wallHalf",
      },
      {
        x: 0,
        z: 5,
        w: 3,
        d: 1,
        side: "south",
        rotationY: Math.PI,
        moduleId: "wallHalf",
      },
    ],
    doorOpenings: [
      { side: "north", offset: 0, width: 1, exitStairsRotationY: Math.PI },
      { side: "south", offset: 0, width: 1, exitStairsRotationY: 0 },
    ],
    enemySpawns: [],
    chestSpawns: [],
    exitMarker: null,
    setDressingModules: [
      {
        x: -1.45,
        z: 0,
        w: 1,
        d: 1,
        side: "west",
        rotationY: Math.PI / 2,
        moduleId: "banner",
      },
      {
        x: 1.45,
        z: 0,
        w: 1,
        d: 1,
        side: "east",
        rotationY: -Math.PI / 2,
        moduleId: "banner",
      },
    ],
    obstacleModules: [],
  },
  {
    id: "exit_room_east_west_02",
    type: "exit",
    name: "East/West Exit 02",
    dimensions: { w: 11, d: 5 },
    floorModules: [
      {
        x: 0,
        z: 0,
        w: 11,
        d: 5,
        moduleId: "floor",
      },
    ],
    walkableAreas: [
      {
        x: 0,
        z: 0,
        w: 11,
        d: 5,
      },
    ],
    wallModules: [
      {
        x: -5,
        z: -2,
        w: 1,
        d: 1,
        corner: "northWest",
        rotationY: 0,
        moduleId: "wallCorner",
      },
      {
        x: 5,
        z: -2,
        w: 1,
        d: 1,
        corner: "northEast",
        rotationY: Math.PI / 2,
        moduleId: "wallCorner",
      },
      {
        x: 5,
        z: 2,
        w: 1,
        d: 1,
        corner: "southEast",
        rotationY: Math.PI,
        moduleId: "wallCorner",
      },
      {
        x: -5,
        z: 2,
        w: 1,
        d: 1,
        corner: "southWest",
        rotationY: -Math.PI / 2,
        moduleId: "wallCorner",
      },
      {
        x: 0,
        z: -2,
        w: 9,
        d: 1,
        side: "north",
        rotationY: 0,
        moduleId: "wallHalf",
      },
      {
        x: 0,
        z: 2,
        w: 9,
        d: 1,
        side: "south",
        rotationY: Math.PI,
        moduleId: "wallHalf",
      },
    ],
    doorwayModules: [
      {
        x: -5,
        z: 0,
        w: 1,
        d: 3,
        side: "west",
        rotationY: Math.PI / 2,
        moduleId: "wallHalf",
      },
      {
        x: 5,
        z: 0,
        w: 1,
        d: 3,
        side: "east",
        rotationY: -Math.PI / 2,
        moduleId: "wallHalf",
      },
    ],
    doorOpenings: [
      { side: "west", offset: 0, width: 1, exitStairsRotationY: -Math.PI / 2 },
      { side: "east", offset: 0, width: 1, exitStairsRotationY: Math.PI / 2 },
    ],
    enemySpawns: [],
    chestSpawns: [],
    exitMarker: null,
    setDressingModules: [
      {
        x: 0,
        z: -1.45,
        w: 1,
        d: 1,
        side: "north",
        rotationY: Math.PI,
        moduleId: "banner",
      },
      {
        x: 0,
        z: 1.45,
        w: 1,
        d: 1,
        side: "south",
        rotationY: 0,
        moduleId: "banner",
      },
    ],
    obstacleModules: [],
  },
];
