export const SHOP_ROOM_TEMPLATES = [
  {
    id: "shop_room_01",
    type: "shop",
    name: "Shop Room 01",
    tags: ["shop", "standard", "open", "north_south"],
    dimensions: { w: 11, d: 11 },
    floorModules: [
      {
        x: 0,
        z: 0,
        w: 11,
        d: 11,
        moduleId: "floor",
      },
    ],
    walkableAreas: [
      {
        x: 0,
        z: 0,
        w: 11,
        d: 11,
      },
    ],
    wallModules: [
      {
        x: -5,
        z: -5,
        w: 1,
        d: 1,
        corner: "northWest",
        rotationY: 0,
        moduleId: "wallCorner",
      },
      {
        x: 5,
        z: -5,
        w: 1,
        d: 1,
        corner: "northEast",
        rotationY: Math.PI / 2,
        moduleId: "wallCorner",
      },
      {
        x: 5,
        z: 5,
        w: 1,
        d: 1,
        corner: "southEast",
        rotationY: Math.PI,
        moduleId: "wallCorner",
      },
      {
        x: -5,
        z: 5,
        w: 1,
        d: 1,
        corner: "southWest",
        rotationY: -Math.PI / 2,
        moduleId: "wallCorner",
      },
      {
        x: -3,
        z: -5,
        w: 3,
        d: 1,
        side: "north",
        rotationY: 0,
        moduleId: "wallHalf",
      },
      {
        x: 3,
        z: -5,
        w: 3,
        d: 1,
        side: "north",
        rotationY: 0,
        moduleId: "wallHalf",
      },
      {
        x: -3,
        z: 5,
        w: 3,
        d: 1,
        side: "south",
        rotationY: Math.PI,
        moduleId: "wallHalf",
      },
      {
        x: 3,
        z: 5,
        w: 3,
        d: 1,
        side: "south",
        rotationY: Math.PI,
        moduleId: "wallHalf",
      },
      {
        x: -5,
        z: -3,
        w: 1,
        d: 3,
        side: "west",
        rotationY: Math.PI / 2,
        moduleId: "wallHalf",
      },
      {
        x: -5,
        z: 3,
        w: 1,
        d: 3,
        side: "west",
        rotationY: Math.PI / 2,
        moduleId: "wallHalf",
      },
      {
        x: 5,
        z: -3,
        w: 1,
        d: 3,
        side: "east",
        rotationY: -Math.PI / 2,
        moduleId: "wallHalf",
      },
      {
        x: 5,
        z: 3,
        w: 1,
        d: 3,
        side: "east",
        rotationY: -Math.PI / 2,
        moduleId: "wallHalf",
      },
    ],
    doorwayModules: [
      {
        x: 0,
        z: -5,
        w: 3,
        d: 1,
        side: "north",
        rotationY: 0,
        moduleId: "wallHalf",
      },
      {
        x: 0,
        z: 5,
        w: 3,
        d: 1,
        side: "south",
        rotationY: Math.PI,
        moduleId: "wallHalf",
      },
      {
        x: -5,
        z: 0,
        w: 1,
        d: 3,
        side: "west",
        rotationY: Math.PI / 2,
        moduleId: "wallHalf",
      },
      {
        x: 5,
        z: 0,
        w: 1,
        d: 3,
        side: "east",
        rotationY: -Math.PI / 2,
        moduleId: "wallHalf",
      },
    ],
    doorOpenings: [
      { side: "north", offset: 0, width: 1 },
      { side: "south", offset: 0, width: 1 },
      { side: "west", offset: 0, width: 1 },
      { side: "east", offset: 0, width: 1 },
    ],
    playerStart: {
      x: 0,
      z: 3.7,
    },
    exitMarker: {
      x: 0,
      z: -3.7,
    },
    shopOfferSpawns: [
      {
        id: "shop_stand_left",
        x: -2.6,
        z: -3.5,
        rotationY: 0,
        altarScale: 0.86,
        collisionSize: { w: 0.86, d: 0.86 },
      },
      {
        id: "shop_stand_center",
        x: 0,
        z: -3.5,
        rotationY: 0,
        altarScale: 0.86,
        collisionSize: { w: 0.86, d: 0.86 },
      },
      {
        id: "shop_stand_right",
        x: 2.6,
        z: -3.5,
        rotationY: 0,
        altarScale: 0.86,
        collisionSize: { w: 0.86, d: 0.86 },
      },
    ],
    enemySpawns: [],
    chestSpawns: [],
    setDressingModules: [],
    obstacleModules: [],
    decorZones: [],
  },
];
