export const TREASURE_ROOM_TEMPLATES = [
  {
    id: "treasure_01",
    type: "treasure",
    name: "Four-Way Treasure Room 01",
    dimensions: { w: 11, d: 11 },
    floorModules: [
      {
        x: 0,
        z: 0,
        w: 11,
        d: 11,
        moduleId: "floor",
      },
    ],
    walkableAreas: [
      {
        x: 0,
        z: 0,
        w: 11,
        d: 11,
      },
    ],
    wallModules: [
      {
        x: -5,
        z: -5,
        w: 1,
        d: 1,
        corner: "northWest",
        rotationY: 0,
        moduleId: "wallCorner",
      },
      {
        x: 5,
        z: -5,
        w: 1,
        d: 1,
        corner: "northEast",
        rotationY: Math.PI / 2,
        moduleId: "wallCorner",
      },
      {
        x: 5,
        z: 5,
        w: 1,
        d: 1,
        corner: "southEast",
        rotationY: Math.PI,
        moduleId: "wallCorner",
      },
      {
        x: -5,
        z: 5,
        w: 1,
        d: 1,
        corner: "southWest",
        rotationY: -Math.PI / 2,
        moduleId: "wallCorner",
      },
      {
        x: -3,
        z: -5,
        w: 3,
        d: 1,
        side: "north",
        rotationY: 0,
        moduleId: "wallHalf",
      },
      {
        x: 3,
        z: -5,
        w: 3,
        d: 1,
        side: "north",
        rotationY: 0,
        moduleId: "wallHalf",
      },
      {
        x: -3,
        z: 5,
        w: 3,
        d: 1,
        side: "south",
        rotationY: -Math.PI,
        moduleId: "wallHalf",
      },
      {
        x: 3,
        z: 5,
        w: 3,
        d: 1,
        side: "south",
        rotationY: -Math.PI,
        moduleId: "wallHalf",
      },
      {
        x: -5,
        z: 0,
        w: 1,
        d: 9,
        side: "west",
        rotationY: Math.PI / 2,
        moduleId: "wallHalf",
      },
      {
        x: 5,
        z: 0,
        w: 1,
        d: 9,
        side: "east",
        rotationY: -Math.PI / 2,
        moduleId: "wallHalf",
      },
    ],
    doorwayModules: [
      {
        x: 0,
        z: -5,
        w: 3,
        d: 1,
        side: "north",
        rotationY: 0,
        moduleId: "wallHalf",
      },
      {
        x: 0,
        z: 5,
        w: 3,
        d: 1,
        side: "south",
        rotationY: Math.PI,
        moduleId: "wallHalf",
      },
      {
        x: -5,
        z: 0,
        w: 1,
        d: 3,
        side: "west",
        rotationY: Math.PI / 2,
        moduleId: "wallHalf",
      },
      {
        x: 5,
        z: 0,
        w: 1,
        d: 3,
        side: "east",
        rotationY: -Math.PI / 2,
        moduleId: "wallHalf",
      },
    ],
    doorOpenings: [
      { side: "north", offset: 0, width: 1 },
      { side: "south", offset: 0, width: 1 },
      { side: "west", offset: 0, width: 1 },
      { side: "east", offset: 0, width: 1 },
    ],
    enemySpawns: [],
    chestSpawns: [
      {
        x: -3.2,
        z: -3.2,
        rotationY: Math.PI / 2,
        modelId: "chest_01",
      },
      {
        x: 3.2,
        z: -3.2,
        rotationY: -Math.PI / 2,
        modelId: "chest_01",
      },
      {
        x: -3.2,
        z: 3.2,
        rotationY: Math.PI / 2,
        modelId: "chest_01",
      },
    ],
    exitMarker: null,
    decorZones: [
      {
        id: "treasure_01_center_scatter",
        type: "treasure",
        x: 0,
        z: 0,
        w: 4,
        d: 4,
      },
    ],
    obstacleModules: [],
  },
  {
    id: "treasure_02",
    type: "treasure",
    name: "treasure_02",
    dimensions: { w: 11, d: 11 },
    floorModules: [
      {
        x: 0,
        z: 0,
        w: 11,
        d: 11,
        moduleId: "floor",
      },
    ],
    walkableAreas: [
      {
        x: 0,
        z: 0,
        w: 11,
        d: 11,
      },
    ],
    wallModules: [
      {
        x: -5,
        z: -5,
        w: 1,
        d: 1,
        corner: "northWest",
        rotationY: 0,
        moduleId: "wallCorner",
      },
      {
        x: 5,
        z: -5,
        w: 1,
        d: 1,
        corner: "northEast",
        rotationY: Math.PI / 2,
        moduleId: "wallCorner",
      },
      {
        x: 5,
        z: 5,
        w: 1,
        d: 1,
        corner: "southEast",
        rotationY: Math.PI,
        moduleId: "wallCorner",
      },
      {
        x: -5,
        z: 5,
        w: 1,
        d: 1,
        corner: "southWest",
        rotationY: -Math.PI / 2,
        moduleId: "wallCorner",
      },
      {
        x: -3,
        z: -5,
        w: 3,
        d: 1,
        side: "north",
        rotationY: 0,
        moduleId: "wallHalf",
      },
      {
        x: 3,
        z: -5,
        w: 3,
        d: 1,
        side: "north",
        rotationY: 0,
        moduleId: "wallHalf",
      },
      {
        x: -3,
        z: 5,
        w: 3,
        d: 1,
        side: "south",
        rotationY: -Math.PI,
        moduleId: "wallHalf",
      },
      {
        x: 3,
        z: 5,
        w: 3,
        d: 1,
        side: "south",
        rotationY: -Math.PI,
        moduleId: "wallHalf",
      },
      {
        x: -5,
        z: 0,
        w: 1,
        d: 9,
        side: "west",
        rotationY: Math.PI / 2,
        moduleId: "wallHalf",
      },
      {
        x: 5,
        z: 0,
        w: 1,
        d: 9,
        side: "east",
        rotationY: -Math.PI / 2,
        moduleId: "wallHalf",
      },
    ],
    doorwayModules: [
      {
        x: 0,
        z: -5,
        w: 3,
        d: 1,
        side: "north",
        rotationY: 0,
        moduleId: "wallHalf",
      },
      {
        x: 0,
        z: 5,
        w: 3,
        d: 1,
        side: "south",
        rotationY: Math.PI,
        moduleId: "wallHalf",
      },
      {
        x: -5,
        z: 0,
        w: 1,
        d: 3,
        side: "west",
        rotationY: Math.PI / 2,
        moduleId: "wallHalf",
      },
      {
        x: 5,
        z: 0,
        w: 1,
        d: 3,
        side: "east",
        rotationY: -Math.PI / 2,
        moduleId: "wallHalf",
      },
    ],
    doorOpenings: [
      { side: "north", offset: 0, width: 1 },
      { side: "south", offset: 0, width: 1 },
      { side: "west", offset: 0, width: 1 },
      { side: "east", offset: 0, width: 1 },
    ],
    enemySpawns: [
      {
        x: 0,
        z: 2.4,
        modelId: "enemy_hog_01",
        patrol: [
          { x: 0, z: 2.4 },
          { x: 2.2, z: 1.6 },
          { x: 2.2, z: -1.6 },
          { x: -2.2, z: -1.6 },
          { x: -2.2, z: 1.6 },
        ],
      },
    ],
    chestSpawns: [
      {
        x: -3.2,
        z: -3.2,
        rotationY: Math.PI / 2,
        modelId: "chest_01",
      },
      {
        x: 3.2,
        z: -3.2,
        rotationY: -Math.PI / 2,
        modelId: "chest_01",
      },
      {
        x: -3.2,
        z: 3.2,
        rotationY: Math.PI / 2,
        modelId: "chest_01",
      },
      {
        x: 3.2,
        z: 3.2,
        rotationY: -Math.PI / 2,
        modelId: "chest_01",
      },
    ],
    exitMarker: null,
    decorZones: [
      {
        id: "treasure_02_center_scatter",
        type: "treasure",
        x: 0,
        z: 0,
        w: 4,
        d: 4,
      },
    ],
    obstacleModules: [],
  },
  {
    id: "treasure_03",
    type: "treasure",
    name: "treasure_03",
    dimensions: { w: 7, d: 7 },
    floorModules: [
      {
        x: 0,
        z: 0,
        w: 7,
        d: 7,
        moduleId: "floor",
      },
    ],
    walkableAreas: [
      {
        x: 0,
        z: 0,
        w: 7,
        d: 7,
      },
    ],
    wallModules: [
      {
        x: -3,
        z: -3,
        w: 1,
        d: 1,
        corner: "northWest",
        rotationY: 0,
        moduleId: "wallCorner",
      },
      {
        x: 3,
        z: -3,
        w: 1,
        d: 1,
        corner: "northEast",
        rotationY: Math.PI / 2,
        moduleId: "wallCorner",
      },
      {
        x: 3,
        z: 3,
        w: 1,
        d: 1,
        corner: "southEast",
        rotationY: Math.PI,
        moduleId: "wallCorner",
      },
      {
        x: -3,
        z: 3,
        w: 1,
        d: 1,
        corner: "southWest",
        rotationY: -Math.PI / 2,
        moduleId: "wallCorner",
      },
      {
        x: -1.5,
        z: -3,
        w: 2,
        d: 1,
        side: "north",
        rotationY: 0,
        moduleId: "wallHalf",
      },
      {
        x: 1.5,
        z: -3,
        w: 2,
        d: 1,
        side: "north",
        rotationY: 0,
        moduleId: "wallHalf",
      },
      {
        x: -1.5,
        z: 3,
        w: 2,
        d: 1,
        side: "south",
        rotationY: Math.PI,
        moduleId: "wallHalf",
      },
      {
        x: 1.5,
        z: 3,
        w: 2,
        d: 1,
        side: "south",
        rotationY: Math.PI,
        moduleId: "wallHalf",
      },
      {
        x: -3,
        z: -2,
        w: 1,
        d: 1,
        side: "west",
        rotationY: Math.PI / 2,
        moduleId: "wallHalf",
      },
      {
        x: -3,
        z: 2,
        w: 1,
        d: 1,
        side: "west",
        rotationY: Math.PI / 2,
        moduleId: "wallHalf",
      },
      {
        x: 3,
        z: -2,
        w: 1,
        d: 1,
        side: "east",
        rotationY: -Math.PI / 2,
        moduleId: "wallHalf",
      },
      {
        x: 3,
        z: 2,
        w: 1,
        d: 1,
        side: "east",
        rotationY: -Math.PI / 2,
        moduleId: "wallHalf",
      },
    ],
    doorwayModules: [
      {
        x: 0,
        z: -3,
        w: 3,
        d: 1,
        side: "north",
        rotationY: 0,
        moduleId: "wallHalf",
      },
      {
        x: 0,
        z: 3,
        w: 3,
        d: 1,
        side: "south",
        rotationY: Math.PI,
        moduleId: "wallHalf",
      },
      {
        x: -3,
        z: 0,
        w: 1,
        d: 3,
        side: "west",
        rotationY: Math.PI / 2,
        moduleId: "wallHalf",
      },
      {
        x: 3,
        z: 0,
        w: 1,
        d: 3,
        side: "east",
        rotationY: -Math.PI / 2,
        moduleId: "wallHalf",
      },
    ],
    doorOpenings: [
      { side: "north", offset: 0, width: 1 },
      { side: "south", offset: 0, width: 1 },
      { side: "west", offset: 0, width: 1 },
      { side: "east", offset: 0, width: 1 },
    ],
    enemySpawns: [],
    chestSpawns: [
      {
        x: 0,
        z: 0,
        rotationY: 0,
        modelId: "chest_01",
      },
    ],
    exitMarker: null,
    decorZones: [
      {
        id: "treasure_03_center_scatter",
        type: "treasure",
        x: 0,
        z: 0,
        w: 3,
        d: 3,
      },
    ],
    obstacleModules: [],
  },
  {
    id: "treasure_04",
    type: "treasure",
    name: "treasure_04",
    dimensions: { w: 15, d: 7 },
    floorModules: [
      {
        x: 0,
        z: 0,
        w: 15,
        d: 7,
        moduleId: "floor",
      },
    ],
    walkableAreas: [
      {
        x: 0,
        z: 0,
        w: 15,
        d: 7,
      },
    ],
    wallModules: [
      {
        x: -7,
        z: -3,
        w: 1,
        d: 1,
        corner: "northWest",
        rotationY: 0,
        moduleId: "wallCorner",
      },
      {
        x: 7,
        z: -3,
        w: 1,
        d: 1,
        corner: "northEast",
        rotationY: Math.PI / 2,
        moduleId: "wallCorner",
      },
      {
        x: 7,
        z: 3,
        w: 1,
        d: 1,
        corner: "southEast",
        rotationY: Math.PI,
        moduleId: "wallCorner",
      },
      {
        x: -7,
        z: 3,
        w: 1,
        d: 1,
        corner: "southWest",
        rotationY: -Math.PI / 2,
        moduleId: "wallCorner",
      },
      {
        x: -3.5,
        z: -3,
        w: 6,
        d: 1,
        side: "north",
        rotationY: 0,
        moduleId: "wallHalf",
      },
      {
        x: 3.5,
        z: -3,
        w: 6,
        d: 1,
        side: "north",
        rotationY: 0,
        moduleId: "wallHalf",
      },
      {
        x: -3.5,
        z: 3,
        w: 6,
        d: 1,
        side: "south",
        rotationY: Math.PI,
        moduleId: "wallHalf",
      },
      {
        x: 3.5,
        z: 3,
        w: 6,
        d: 1,
        side: "south",
        rotationY: Math.PI,
        moduleId: "wallHalf",
      },
      {
        x: -7,
        z: -2,
        w: 1,
        d: 1,
        side: "west",
        rotationY: Math.PI / 2,
        moduleId: "wallHalf",
      },
      {
        x: -7,
        z: 2,
        w: 1,
        d: 1,
        side: "west",
        rotationY: Math.PI / 2,
        moduleId: "wallHalf",
      },
      {
        x: 7,
        z: -2,
        w: 1,
        d: 1,
        side: "east",
        rotationY: -Math.PI / 2,
        moduleId: "wallHalf",
      },
      {
        x: 7,
        z: 2,
        w: 1,
        d: 1,
        side: "east",
        rotationY: -Math.PI / 2,
        moduleId: "wallHalf",
      },
    ],
    doorwayModules: [
      {
        x: 0,
        z: -3,
        w: 3,
        d: 1,
        side: "north",
        rotationY: 0,
        moduleId: "wallHalf",
      },
      {
        x: 0,
        z: 3,
        w: 3,
        d: 1,
        side: "south",
        rotationY: Math.PI,
        moduleId: "wallHalf",
      },
      {
        x: -7,
        z: 0,
        w: 1,
        d: 3,
        side: "west",
        rotationY: Math.PI / 2,
        moduleId: "wallHalf",
      },
      {
        x: 7,
        z: 0,
        w: 1,
        d: 3,
        side: "east",
        rotationY: -Math.PI / 2,
        moduleId: "wallHalf",
      },
    ],
    doorOpenings: [
      { side: "north", offset: 0, width: 1 },
      { side: "south", offset: 0, width: 1 },
      { side: "west", offset: 0, width: 1 },
      { side: "east", offset: 0, width: 1 },
    ],
    enemySpawns: [],
    chestSpawns: [
      {
        x: -3.6,
        z: 0,
        rotationY: Math.PI / 2,
        modelId: "chest_01",
      },
      {
        x: 3.6,
        z: 0,
        rotationY: -Math.PI / 2,
        modelId: "chest_01",
      },
    ],
    exitMarker: null,
    decorZones: [
      {
        id: "treasure_04_center_scatter",
        type: "treasure",
        x: 0,
        z: 0,
        w: 5,
        d: 3,
      },
    ],
    obstacleModules: [],
  },
  {
    id: "treasure_side_01",
    type: "treasure",
    name: "Side Treasure Room 01",
    dimensions: { w: 9, d: 9 },
    floorModules: [
      {
        x: 0,
        z: 0,
        w: 9,
        d: 9,
        moduleId: "floor",
      },
    ],
    walkableAreas: [
      {
        x: 0,
        z: 0,
        w: 9,
        d: 9,
      },
    ],
    wallModules: [
      {
        x: -4,
        z: -4,
        w: 1,
        d: 1,
        corner: "northWest",
        rotationY: 0,
        moduleId: "wallCorner",
      },
      {
        x: 4,
        z: -4,
        w: 1,
        d: 1,
        corner: "northEast",
        rotationY: Math.PI / 2,
        moduleId: "wallCorner",
      },
      {
        x: 4,
        z: 4,
        w: 1,
        d: 1,
        corner: "southEast",
        rotationY: Math.PI,
        moduleId: "wallCorner",
      },
      {
        x: -4,
        z: 4,
        w: 1,
        d: 1,
        corner: "southWest",
        rotationY: -Math.PI / 2,
        moduleId: "wallCorner",
      },
      {
        x: 0,
        z: -4,
        w: 7,
        d: 1,
        side: "north",
        rotationY: 0,
        moduleId: "wallHalf",
      },
      {
        x: 0,
        z: 4,
        w: 7,
        d: 1,
        side: "south",
        rotationY: Math.PI,
        moduleId: "wallHalf",
      },
      {
        x: -4,
        z: 0,
        w: 1,
        d: 7,
        side: "west",
        rotationY: Math.PI / 2,
        moduleId: "wallHalf",
      },
      {
        x: 4,
        z: 0,
        w: 1,
        d: 7,
        side: "east",
        rotationY: -Math.PI / 2,
        moduleId: "wallHalf",
      },
    ],
    doorwayModules: [
      {
        x: -4,
        z: 0,
        w: 1,
        d: 3,
        side: "west",
        rotationY: Math.PI / 2,
        moduleId: "wallHalf",
      },
    ],
    doorOpenings: [
      { side: "west", offset: 0, width: 1 },
    ],
    enemySpawns: [],
    chestSpawns: [
      {
        x: 1.8,
        z: -2.1,
        rotationY: -Math.PI / 2,
        modelId: "chest_01",
      },
      {
        x: 1.8,
        z: 2.1,
        rotationY: -Math.PI / 2,
        modelId: "chest_01",
      },
    ],
    exitMarker: null,
    decorZones: [
      {
        id: "treasure_side_01_center_scatter",
        type: "treasure",
        x: 0.6,
        z: 0,
        w: 4,
        d: 4,
      },
    ],
    obstacleModules: [],
  },
  {
    id: "treasure_side_02",
    type: "treasure",
    name: "Side Treasure Room 02",
    dimensions: { w: 9, d: 9 },
    floorModules: [
      {
        x: 0,
        z: 0,
        w: 9,
        d: 9,
        moduleId: "floor",
      },
    ],
    walkableAreas: [
      {
        x: 0,
        z: 0,
        w: 9,
        d: 9,
      },
    ],
    wallModules: [
      {
        x: -4,
        z: -4,
        w: 1,
        d: 1,
        corner: "northWest",
        rotationY: 0,
        moduleId: "wallCorner",
      },
      {
        x: 4,
        z: -4,
        w: 1,
        d: 1,
        corner: "northEast",
        rotationY: Math.PI / 2,
        moduleId: "wallCorner",
      },
      {
        x: 4,
        z: 4,
        w: 1,
        d: 1,
        corner: "southEast",
        rotationY: Math.PI,
        moduleId: "wallCorner",
      },
      {
        x: -4,
        z: 4,
        w: 1,
        d: 1,
        corner: "southWest",
        rotationY: -Math.PI / 2,
        moduleId: "wallCorner",
      },
      {
        x: 0,
        z: -4,
        w: 7,
        d: 1,
        side: "north",
        rotationY: 0,
        moduleId: "wallHalf",
      },
      {
        x: 0,
        z: 4,
        w: 7,
        d: 1,
        side: "south",
        rotationY: Math.PI,
        moduleId: "wallHalf",
      },
      {
        x: -4,
        z: 0,
        w: 1,
        d: 7,
        side: "west",
        rotationY: Math.PI / 2,
        moduleId: "wallHalf",
      },
      {
        x: 4,
        z: 0,
        w: 1,
        d: 7,
        side: "east",
        rotationY: -Math.PI / 2,
        moduleId: "wallHalf",
      },
    ],
    doorwayModules: [
      {
        x: -4,
        z: 0,
        w: 1,
        d: 3,
        side: "west",
        rotationY: Math.PI / 2,
        moduleId: "wallHalf",
      },
    ],
    doorOpenings: [
      { side: "west", offset: 0, width: 1 },
    ],
    enemySpawns: [
      {
        x: 1.6,
        z: -1.8,
        modelId: "enemy_hog_01",
        patrol: [
          { x: 1.6, z: -1.8 },
          { x: 2.6, z: 1.2 },
          { x: 0.5, z: 2.5 },
          { x: 0.3, z: -2.8 },
        ],
      },
      {
        x: 2.7,
        z: 2,
        modelId: "enemy_hog_01",
        patrol: [
          { x: 2.7, z: 2 },
          { x: 1.7, z: -2.5 },
          { x: -0.5, z: -1.1 },
          { x: -0.4, z: 2.5 },
        ],
      },
    ],
    chestSpawns: [],
    exitMarker: null,
    decorZones: [
      {
        id: "treasure_side_02_center_scatter",
        type: "treasure",
        x: 0.6,
        z: 0,
        w: 4,
        d: 4,
      },
    ],
    obstacleModules: [],
  },
];
